# Model configuration for children's books rating prediction

sample_size: 10000  # Set to null for full dataset
test_size: 0.2

model:
  type: "xgboost"
  params:
    n_estimators: 300
    learning_rate: 0.05
    max_depth: 10
    subsample: 0.85
    colsample_bytree: 0.85
    reg_alpha: 0.1
    reg_lambda: 1.0
    random_state: 42
    n_jobs: -1

#   type: "xgboost"  # RMSE: 0.3415 Test MAE: 0.2552 Test R²: 0.0921
#   params:
#     n_estimators: 200
#     learning_rate: 0.1
#     max_depth: 8
#     subsample: 0.8
#     colsample_bytree: 0.8
#     random_state: 42


  # type: "gradient_boosting"  # RMSE: 0.3412 Test MAE: 0.2544 Test R²: 0.0939
  # params:
  #   n_estimators: 100
  #   learning_rate: 0.1
  #   max_depth: 6
  #   random_state: 42

# Alternative configurations for experimentation
# Uncomment to try different models:

# model:
#   type: "random_forest"
#   params:
#     n_estimators: 100
#     max_depth: 10
#     random_state: 42
#     n_jobs: -1